# Keys are obtained from your Mimecast account, see
# https://community.mimecast.com/s/article/Managing-API-Applications-505230018
# See https://integrations.mimecast.com/documentation/api-overview/global-base-urls/ for a list of Base URLs
# Use the Base URL that corresponds to the location of your account

base_url = ""
access_key = ""
secret_key = ""
app_id = ""
app_key = ""
